export const CHANGE_TEXT = 'EMPLOYEE_FORM_CHANGE_TEXT'

export const SAVE_EMPLOYEE_START = 'EMPLOYEE_FORM_SAVE_EMPLOYEE_START'
export const SAVE_EMPLOYEE_FULFILLED = 'EMPLOYEE_FORM_SAVE_EMPLOYEE_FULFILLED'
export const SAVE_EMPLOYEE_REJECTED = 'EMPLOYEE_FORM_SAVE_EMPLOYEE_REJECTED'
